//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qianli.web.Models.v
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toutiao
    {
        public int Id { get; set; }
        public string detailUrl { get; set; }
        public Nullable<bool> isDouble11 { get; set; }
        public Nullable<int> form { get; set; }
        public Nullable<int> favourCount { get; set; }
        public Nullable<int> viewNum { get; set; }
        public string showDate { get; set; }
        public string feedId { get; set; }
        public Nullable<int> showWeight { get; set; }
        public string publishId { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public string bizSourceName { get; set; }
        public string picList { get; set; }
        public string content { get; set; }
        public Nullable<int> columnId { get; set; }
        public string subColumn { get; set; }
    }
}
